export const AUTH_LOGIN_FAIL = "AUTH_LOGIN_FAIL";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_START = "AUTH_LOGIN_START";

export const AUTH_HANDLE_USER = "AUTH_HANDLE_USER";
export const GET_USER_INFO = "GET_USER_INFO";
